version: "3.7"

services:

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/app
    depends_on:
      - postgres
      - mailer

  postgres:
    container_name: postgresql
    image: postgres:12.1-alpine
    volumes:
      - ./var/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

  mailer:
    container_name: mailer
    image: mailhog/mailhog
    ports:
      - "8082:8025"